### ISSUE TITLE
Is it possible to get a arm64 macOS build?

### ISSUE THREAD

**Issue by psobolewskiPhD** [conda-forge/fastremap-feedstock#3]
### Comment:

At present, there is no am64 macOS binary on conda-forge. But the module does build if installed from source via pypi. Would it be possible to add a binary for arm64 macOS ?

**Comment by william-silversmith** [comment]
Hi Peter, I would accept a PR that adds support for this. I'm too loaded with projects to also research this right now and do it myself. It would be a welcome addition.

**Comment by hmaarrfk** [comment]
bot should get to work!

**Comment by goanpeca** [comment]
https://github.com/conda-forge/fastremap-feedstock/pull/4 has been merged. @psobolewskiPhD could you check in a couple of hours (I am guessing it will take that amount of time) and check if things work as expected?

Cheers!

**Comment by psobolewskiPhD** [comment]
Will do!
This is because cellulose is on conda-forge on arm64, but this module is a depend, so it doesn't install.

**Comment by william-silversmith** [comment]
Looks like the files are generated. Let me know if it works.

**Comment by psobolewskiPhD** [comment]
Not live yet 😄 
```
Executing the query fastremap

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
```

**Comment by psobolewskiPhD** [comment]
Looks good now:
```
Executing the query fastremap

conda-forge/osx-arm64                              @   1.3MB/s  1.9s
conda-forge/noarch                                 @   1.0MB/s  8.3s


 Name      Version Build           Channel              
─────────────────────────────────────────────────────────
 fastremap 1.12.2  py310ha6127ee_2 conda-forge/osx-arm64
 fastremap 1.12.2  py38h7fa088a_2  conda-forge/osx-arm64
 fastremap 1.12.2  py39hc86685f_2  conda-forge/osx-arm64
```
Installing cellpose as we speak!

...and it works fine.
Thanks everyone!
❤️

**Comment by william-silversmith** [comment]
Fantastic! Good luck with your research Peter.

**Comment by william-silversmith** [comment]
Thanks for helping with this Gonzalo and Mark!
